version: '3'
services:

  app:
    container_name: app

    image: php74

    # Adapt these
    volumes:
      - ./:/var/www
      - ./htdocs/:/var/www/html

    ports:
      - "8080:80"
      - "443:443"
